// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgKzBuz_poGrVGeF8-1UgO7PAvVSpZoeg',
    appId: '1:930925120838:web:5c3129ff1df7d084e76947',
    messagingSenderId: '930925120838',
    projectId: 'goschool-36c8e',
    authDomain: 'goschool-36c8e.firebaseapp.com',
    storageBucket: 'goschool-36c8e.firebasestorage.app',
    measurementId: 'G-YY826Q6DDY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-JBdvM5IK2yVAoL8tRtNnC_LYIxc_hRQ',
    appId: '1:930925120838:android:1c552032e705f43de76947',
    messagingSenderId: '930925120838',
    projectId: 'goschool-36c8e',
    storageBucket: 'goschool-36c8e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtjkIT48256IuGFO9IhAuvLJYhhXFG4R4',
    appId: '1:930925120838:ios:cc96a477d87f547be76947',
    messagingSenderId: '930925120838',
    projectId: 'goschool-36c8e',
    storageBucket: 'goschool-36c8e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtjkIT48256IuGFO9IhAuvLJYhhXFG4R4',
    appId: '1:930925120838:ios:cc96a477d87f547be76947',
    messagingSenderId: '930925120838',
    projectId: 'goschool-36c8e',
    storageBucket: 'goschool-36c8e.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgKzBuz_poGrVGeF8-1UgO7PAvVSpZoeg',
    appId: '1:930925120838:web:1b5221a8afa94f53e76947',
    messagingSenderId: '930925120838',
    projectId: 'goschool-36c8e',
    authDomain: 'goschool-36c8e.firebaseapp.com',
    storageBucket: 'goschool-36c8e.firebasestorage.app',
    measurementId: 'G-DJE4QMF0L3',
  );
}
